### ISSUE TITLE
Renders in white and grey with no transparency or blur on linux systems

### ISSUE THREAD

**Issue by playerofceleste** [DoubleDotGames/Quartz#3]
Using the .AppImage and AppImageLauncher using the Wayland based compositor "Hyprland" results in a broken application as shown below.
![image](https://github.com/DoubleDotGames/Quartz/assets/96972638/337dccab-ff2d-4a97-b816-046606c3434e)
I am running arch linux

**Comment by DoubleDotGames** [comment]
I will attempt to address this issue in an upcoming update however I'm not sure how long the fix will take to add. 
Thank you for bringing this to my attention.

**Comment by Harrex** [comment]
Found a solution to this - In the new `BrowserWindow ({...})` under `CreateWindow`, I just added the `transparent: true` property, and everything seems to work as it should. (I'm also on Hyprland in the screenshot below)
![image](https://github.com/DoubleDotGames/Quartz/assets/54386443/8498ab0b-47cd-4565-9cf8-e32e7cea96d9)

I'll be submitting a PR for this once I:
- Verify it for Mac (I'll get onto a uni computer in the morning to have a look)
   I'll play around with this transparency toggle on mac as well as linux, because it seems to be an actual electron change and the old way is breaking on MacOS14.0.1
- Make sure I haven't broken it on the regular linux desktops

**Comment by DoubleDotGames** [comment]
I'm going to close this since this issue seems to be fixed. @Harrex Your PR has been accepted and merged with the main branch. Thank you for contributing
